### ISSUE TITLE
MVP #3: Search Capability

### ISSUE THREAD

**Issue by nmhalloran** [nmhalloran/modern-hospitium#4]
MVP # 3 - Search Capability 

- [ ] Locations are hard-coded into system. User can search for any included locations in a functional search bar
- [ ] Adequate styling
- [ ] Smooth, bug-free navigation
- [ ] Seeded with info to demonstrate this feature

**Comment by AAlfarho** [comment]
Great job on the search.
Kudos for the attention to detail with the disappearing animation.
With the current state of the live site, we can consider the MVP deliverable complete.

The more seeding we add the better, but currently, this is adequate.
